### ISSUE TITLE
use asyncio.Queue

### ISSUE THREAD

**Issue by pjz** [michalc/asyncio-buffered-pipeline#1]
Your comment says:

        # The regular asyncio.queue doesn't have a function to wait for space
        # in the queue, which we need so we don't iterate upstream until there
        # is space.

which isn't true.  calling `await q.put(item)` will wait (block) until there's room in
the queue for the specified item... if a queue maxsize is defined.

**Comment by michalc** [comment]
So yes, the comment is perhaps a bit unclear. Maybe it should read

"The regular asyncio.queue doesn't have a function that only waits for space in the queue"

The call `await q.put(item)` does wait, but it _also_ puts the item into the queue. I wanted these things separate since...

Previous versions of asyncio-buffered-pipeline used asyncio.queue, but I couldn't think of a way to use it that made `buffer_size` accurate. Specifically, I wanted a `buffer_size` of 1 to be the default. However using asyncio.queue, with a `maxsize` of 1, then the number of items buffered by the `buffered_iterator`, would actually be 2, since at the point of calling `await q.put(item)`, there could be one item already in the queue, and another in memory in the `item` variable.

The only way I could think to actually have a buffer size of 1, was to write my own queue that offered a way to wait for space, and only then iterated upstream to fetch the item once space was available.

**Comment by michalc** [comment]
I've changed the comment to read
```
# The regular asyncio.queue doesn't have a function to wait for space
# in the queue without also immediately putting an item into it, which
# would mean effective minimum buffer_size is 2: an item in the queue
# and in memory waiting to put into it. To allow a buffer_size of 1,
# we need to check there is space _before_ fetching the item from
# upstream. This requires a custom queue implementation.
```
Closing this issue, but feel free to re-open.

**Comment by pjz** [comment]
I understand your objection, and have, I think, fixed it (in a method similar to how you implement the internals of yours) at https://github.com/pjz/iterbuff/commit/82b89a6c128a387638cd32007b80d511fbf2758e#diff-69596987bef09d8f8daff6999288926f
 .  I also made it a decorator b/c I think that looks a bit nicer, but that's orthogonal to solving the maxsize-in-memory-at-once problem.

**Comment by michalc** [comment]
Ah interesting... so determining there _must_ be space in the queue after `get`ing from it, and then only waiting on this if the queue is full after `put`ing to it, so never filling up "maxsize+1" of memory

I think I'm probably still anti using this pattern in this project though. It's probably mostly preference, but my reasons are:

- It has a slightly different flow/logic for the case when the queue is full [that is not abstracted away "inside" the queue]
- Its consumer communicates to the producer using 2 "signals": getting something from the queue, and setting the Event.
- Which makes me wonder if there is a race condition between them somehow? Not saying there is, but I'm finding it hard to convince myself there isn't.
- The 3 steps in my head that need to be ordered

    1. Wait for space in the downstream queue
    2. Iterate upstream
    3. Put in the downstream queue

    <br />map clearly (for me) to the code in this project:

    ```
    await queue_space()
    value = await iterator.__anext__()
    queue_put((None, value))
    ```

Also the decorator pattern. I did consider this... However, is there a chance that in a pipeline, if downstream generators don't finish, say, an exception is raised, then tasks for the upstream won't notice, will be sitting there waiting forever?

**Comment by michalc** [comment]
Ah! Although, for some reason I didn't use `clear` in the queue Events. So I am tempted to use them instead of creating new Event objects...

**Comment by pjz** [comment]
re: race condition:
Remember that there's only one execution thread through all of this, that can swap between tasks at any async/await boundary, so there's no race condition.

re: the looping:
Since the queue starts out empty, your steps 1,2,3 are safe to reorder as 2,3,1, which is essentially what my code in lines 57..63 does.

re: downstream generators not finishing:
I... guess?  but that's the same risk as any async code that spawns and manages a background task.  In your example code, if you raise an exception inside the for loop, after the `print(val)`, you'll see a complaint about unfinished tasks in the background.  It won't stop the code from exiting - they're not real threads :)

Overall it's a bit of a toss-up I guess.  I think  mine is a slightly simpler implementation.  You do point out some valid deficiencies in the asyncio.Queue class, though (would adding a `async def not_full(self)` to the built-in Queue would be all you need?)
